info:
  app:
    name: Videostore
    description: Videostore kata

spring:
  http.encoding.force: true
  mandatory-file-encoding: UTF-8
  jpa.hibernate.ddl-auto: validate
  profiles:
    active: dev

liquibase.change-log: classpath:db/changelog/db.changelog.xml

management:
  context-path: /status

logging.level.root: INFO
logging.level.pl.artcoder.videostore: INFO
